# read_excel
* [데이터 다운로드 링크](https://www.kaggle.com/ruchi798/shopping-cart-database?select=sales.csv)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd

customer_df = pd.read_csv('/content/drive/MyDrive/data/customers.csv', sep=',')

In [2]:
customer_df.tail(10)

     customer_id        customer_name  ...              state    country
990          991     Cristina Jowling  ...           Tasmania  Australia
991          992  Meredith Stansfield  ...         Queensland  Australia
992          993      Orella Singyard  ...           Victoria  Australia
993          994        Vanna Densham  ...  Western Australia  Australia
994          995        Leandra Derks  ...  Western Australia  Australia
995          996       Elvira Sarfati  ...           Tasmania  Australia
996          997       Dickie Grushin  ...           Tasmania  Australia
997          998       Rebecka Fabler  ...         Queensland  Australia
998          999       Carita Vynarde  ...  Western Australia  Australia
999         1000     Mandel Fairbanks  ...           Tasmania  Australia

[10 rows x 9 columns]

In [ ]:
customer_df = pd.read_excel('/content/drive/MyDrive/data/customers.xlxs')

In [ ]:
customer_df

In [ ]:
customer_df.count()

In [ ]:
customer_df.head(3)