# read_excel
* [데이터 다운로드 링크](https://www.kaggle.com/ruchi798/shopping-cart-database?select=sales.csv)

In [1]:
import pandas as pd

In [2]:
products_df = pd.read_csv('/content/drive/MyDrive/data/products.csv')
products_df.head()

   product_ID  ...                                   description
0           0  ...  A red coloured, XS sized, Oxford Cloth Shirt
1           1  ...   A red coloured, S sized, Oxford Cloth Shirt
2           2  ...   A red coloured, M sized, Oxford Cloth Shirt
3           3  ...   A red coloured, L sized, Oxford Cloth Shirt
4           4  ...  A red coloured, XL sized, Oxford Cloth Shirt

[5 rows x 8 columns]

In [3]:
# NULL 값 체크
products_df.isnull().sum()

product_ID      0
product_type    0
product_name    0
size            0
colour          0
price           0
quantity        0
description     0
dtype: int64

In [4]:
# value 별로 몇 개의 데이터 있는지 확인
products_df['size'].value_counts()

XS    252
S     252
M     252
L     252
XL    252
Name: size, dtype: int64

In [5]:
# 기초 통계
products_df['quantity'].describe()

count    1260.000000
mean       60.150000
std        11.670573
min        40.000000
25%        50.000000
50%        60.000000
75%        70.000000
max        80.000000
Name: quantity, dtype: float64

In [6]:
products_df['quantity'].min()

40

In [7]:
products_df['quantity'].sum()

75789

In [8]:
products_df['quantity'].max()

80

In [9]:
products_df['quantity'].median()

60.0

In [10]:
products_df.groupby(['product_type', 'size']).size()

product_type  size
Jacket        L       84
              M       84
              S       84
              XL      84
              XS      84
Shirt         L       84
              M       84
              S       84
              XL      84
              XS      84
Trousers      L       84
              M       84
              S       84
              XL      84
              XS      84
dtype: int64

In [11]:
products_df.groupby(['product_type', 'size']).count()

                   product_ID  product_name  ...  quantity  description
product_type size                            ...
Jacket       L             84            84  ...        84           84
             M             84            84  ...        84           84
             S             84            84  ...        84           84
             XL            84            84  ...        84           84
             XS            84            84  ...        84           84
Shirt        L             84            84  ...        84           84
             M             84            84  ...        84           84
             S             84            84  ...        84           84
             XL            84            84  ...        84           84
             XS            84            84  ...        84           84
Trousers     L             84            84  ...        84           84
             M             84            84  ...        84           84
             S             84            84  ...        84           84
             XL            84            84  ...        84           84
             XS            84            84  ...        84           84

[15 rows x 6 columns]

In [12]:
products_df.groupby(['product_type', 'size']).quantity.sum()

product_type  size
Jacket        L       5141
              M       4968
              S       5012
              XL      5071
              XS      5195
Shirt         L       5365
              M       4977
              S       4991
              XL      4976
              XS      4954
Trousers      L       5084
              M       4915
              S       5029
              XL      5023
              XS      5088
Name: quantity, dtype: int64

In [13]:
products_df.groupby(['product_type', 'size']).agg({
    'price':['min', 'max', 'median'],
    'quantity':['mean', 'median', 'nunique', 'std', 'sum'],
    'colour':['nunique']
})

                  price               quantity  ...                           colour
                    min  max median       mean  ... nunique        std   sum nunique
product_type size                               ...
Jacket       L       90  119  111.0  61.202381  ...      37  12.411401  5141       7
             M       90  119  111.0  59.142857  ...      36  11.625836  4968       7
             S       90  119  111.0  59.666667  ...      34  12.215271  5012       7
             XL      90  119  111.0  60.369048  ...      36  11.445818  5071       7
             XS      90  119  111.0  61.845238  ...      39  11.340825  5195       7
Shirt        L       92  119  112.5  63.869048  ...      32  11.375073  5365       7
             M       92  119  112.5  59.250000  ...      35  10.276743  4977       7
             S       92  119  112.5  59.416667  ...      38  11.852719  4991       7
             XL      92  119  112.5  59.238095  ...      37  12.101597  4976       7
             XS      92  119  112.5  58.976190  ...      38  10.956624  4954       7
Trousers     L       90  119   99.5  60.523810  ...      36  12.395565  5084       7
             M       90  119   99.5  58.511905  ...      35  11.584674  4915       7
             S       90  119   99.5  59.869048  ...      37  11.603676  5029       7
             XL      90  119   99.5  59.797619  ...      33  11.909073  5023       7
             XS      90  119   99.5  60.571429  ...      36  11.639449  5088       7

[15 rows x 9 columns]

In [14]:
agg_df = products_df.groupby(['product_type', 'size']).agg({
    'price' : ['min', 'max', 'median'],
    'quantity' : ['mean', 'median', 'nunique', 'std', 'sum'],
    'colour' : ['nunique']
})

# products_df.groupby(['product_type', 'size']).agg({
#     'price' : ['min', 'max', 'median'],
#     'quantity' : ['mean', 'median', 'nunique', 'std', 'sum'],
#     'colour' : ['nunique']
# })

In [15]:
agg_df.head()

                  price               quantity  ...                           colour
                    min  max median       mean  ... nunique        std   sum nunique
product_type size                               ...
Jacket       L       90  119  111.0  61.202381  ...      37  12.411401  5141       7
             M       90  119  111.0  59.142857  ...      36  11.625836  4968       7
             S       90  119  111.0  59.666667  ...      34  12.215271  5012       7
             XL      90  119  111.0  60.369048  ...      36  11.445818  5071       7
             XS      90  119  111.0  61.845238  ...      39  11.340825  5195       7

[5 rows x 9 columns]

In [16]:
agg_df['quantity']['mean']

product_type  size
Jacket        L       61.202381
              M       59.142857
              S       59.666667
              XL      60.369048
              XS      61.845238
Shirt         L       63.869048
              M       59.250000
              S       59.416667
              XL      59.238095
              XS      58.976190
Trousers      L       60.523810
              M       58.511905
              S       59.869048
              XL      59.797619
              XS      60.571429
Name: mean, dtype: float64

In [17]:
agg_df['quantity']['mean']['Jacket']['L']

61.20238095238095

In [18]:
products_df.head()

   product_ID  ...                                   description
0           0  ...  A red coloured, XS sized, Oxford Cloth Shirt
1           1  ...   A red coloured, S sized, Oxford Cloth Shirt
2           2  ...   A red coloured, M sized, Oxford Cloth Shirt
3           3  ...   A red coloured, L sized, Oxford Cloth Shirt
4           4  ...  A red coloured, XL sized, Oxford Cloth Shirt

[5 rows x 8 columns]

In [ ]:
products_df[products_df['colour'].isin(['red', 'black'])]

In [24]:
products_df[products_df['description'].str.contains('XS sized|XL sized')]

      product_ID  ...                                        description
0              0  ...       A red coloured, XS sized, Oxford Cloth Shirt
4              4  ...       A red coloured, XL sized, Oxford Cloth Shirt
5              5  ...    A orange coloured, XS sized, Oxford Cloth Shirt
9              9  ...    A orange coloured, XL sized, Oxford Cloth Shirt
10            10  ...    A yellow coloured, XS sized, Oxford Cloth Shirt
...          ...  ...                                                ...
1249        1249  ...  A blue coloured, XL sized, Tracksuit Bottoms T...
1250        1250  ...  A indigo coloured, XS sized, Tracksuit Bottoms...
1254        1254  ...  A indigo coloured, XL sized, Tracksuit Bottoms...
1255        1255  ...  A violet coloured, XS sized, Tracksuit Bottoms...
1259        1259  ...  A violet coloured, XL sized, Tracksuit Bottoms...

[504 rows x 8 columns]

In [25]:
products_df

      product_ID  ...                                        description
0              0  ...       A red coloured, XS sized, Oxford Cloth Shirt
1              1  ...        A red coloured, S sized, Oxford Cloth Shirt
2              2  ...        A red coloured, M sized, Oxford Cloth Shirt
3              3  ...        A red coloured, L sized, Oxford Cloth Shirt
4              4  ...       A red coloured, XL sized, Oxford Cloth Shirt
...          ...  ...                                                ...
1255        1255  ...  A violet coloured, XS sized, Tracksuit Bottoms...
1256        1256  ...  A violet coloured, S sized, Tracksuit Bottoms ...
1257        1257  ...  A violet coloured, M sized, Tracksuit Bottoms ...
1258        1258  ...  A violet coloured, L sized, Tracksuit Bottoms ...
1259        1259  ...  A violet coloured, XL sized, Tracksuit Bottoms...

[1260 rows x 8 columns]

In [26]:
products_df['size'].replace('XS', 'S')

0        S
1        S
2        M
3        L
4       XL
        ..
1255     S
1256     S
1257     M
1258     L
1259    XL
Name: size, Length: 1260, dtype: object